### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by rlemay0607** [mvenghaus/filament-plugin-ai-writer#1]
When I am trying to setup the plugin I am getting the following error. 
Class "App\Providers\Filament\Mvenghaus\FilamentPluginAIWriter\Integration\OpenAI" not found

**Comment by mvenghaus** [comment]
Hey,

seems like the path resolved relative .. is your import correct else try the fqcn:

\Mvenghaus\FilamentPluginAIWriter\Integration\OpenAI

**Comment by rlemay0607** [comment]
Now I get this error
Class "Mvenghaus\FilamentPluginAIWriter\Integration\OpenAI" not found

**Comment by mvenghaus** [comment]
Oh .. sorry .. there are little typos in documentation.

use Mvenghaus\FilamentPluginAiWriter\Integration\OpenAI;
use Mvenghaus\FilamentPluginAiWriter\Integration\OpenAI\Models\Gpt4;

->

use Mvenghaus\FilamentPluginAIWriter\Integrations\OpenAI\OpenAI;
use Mvenghaus\FilamentPluginAIWriter\Integrations\OpenAI\Models\Gpt4;

**Comment by rlemay0607** [comment]
Thanks for that change that worked now I am getting an error when I add a button.  is this part correct:
use Mvenghaus\FilamentPluginAiWriter\Forms\Components\AIWriterButton;

**Comment by mvenghaus** [comment]
i should copy all namespaces :) 

FilamentPluginAiWriter -> FilamentPluginAIWriter

the "i" should be uppercase
