### ISSUE TITLE
Not really an issue but question

### ISSUE THREAD

**Issue by scottjo** [mvenghaus/filament-plugin-ai-writer#2]
Hi - using this plugin, using the example code if I set the target to a text field It works a treat, 

`->target(fn(Set $set, Response $response) => $set('target_field', $response->text))`

If, however, my 'target_field' is a rich text field, nothing seems to work. What's the best solution? Thanks in advance

**Comment by mvenghaus** [comment]
Hey @scottjo,

mmh .. seems like a filament bug. I think the rich editor is reinitialized on update.. the content appears for a little moment.

The only solution I can find at the moment is the following. If I find a better one I will post it here.

```php
->target(function($livewire, Response $response) {
    $livewire->js("document.getElementById('data.target_field').innerHTML=`" . $response->text . "`");
})
```

**Comment by scottjo** [comment]
Thanks very much - I thought I was going mad!
